FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY PMZuuIAPIGateway/target/PMZuuIAPIGateway-0.0.1-SNAPSHOT.jar /opt/lib/
COPY zuui-entrypoint.sh /opt/bin/zuui-entrypoint.sh
RUN chmod 755 /opt/bin/zuui-entrypoint.sh
EXPOSE 8095
