FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY target/ProjectManagerProjectAPI-0.0.1-SNAPSHOT.jar /opt/lib/
COPY projectservice-entrypoint.sh /opt/bin/projectservice-entrypoint.sh
RUN chmod 755 /opt/bin/projectservice-entrypoint.sh
EXPOSE 0
