FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY ProjectManagerUserAPI/target/ProjectManagerUserAPI-0.0.1-SNAPSHOT.jar /opt/lib/
COPY userservice-entrypoint.sh /opt/bin/userservice-entrypoint.sh
RUN chmod 755 /opt/bin/userservice-entrypoint.sh
EXPOSE 0
