version: '3.5'
services:

  projectmanagermysqldb:
    image: mysql:8
    networks:
      - projectmanager-network
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
      - MYSQL_DATABASE=pmsdb 

  eureka-server:
    image: eureka-server
    ports:
      - "9091:9091"
    environment:
      - server.port=9091
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka
    networks:
      - projectmanager-network
        
  userservice:
    image: userservice
    restart: always
    networks:
      - projectmanager-network
    environment:
      - spring.profiles.active=dockerDb
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka
    entrypoint: java -jar /opt/lib/ProjectManagerUserAPI-0.0.1-SNAPSHOT.jar
    depends_on:
      - eureka-server
      - projectmanagermysqldb

  projectservice:
    image: projectservice
    restart: always
    networks:
      - projectmanager-network
    environment:
      - spring.profiles.active=dockerDb
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka
    depends_on:
      - eureka-server
      - projectmanagermysqldb
    entrypoint: java -jar /opt/lib/ProjectManagerProjectAPI-0.0.1-SNAPSHOT.jar
    
  pmzuuiservice:
    image: pmzuuiservice
    restart: always
    networks:
      - projectmanager-network
    environment:
       - server.port=8095
       - eureka.client.serviceUrl.defaultZone=http://eureka-server:9091/eureka
    restart: on-failure
    depends_on:
      - eureka-server
    
  projectmanagerui:
    image: projectmanagerui
    ports:
      - "4201:4201"
    networks:
      - projectmanager-network
    environment:
      - port=4201
    depends_on:
      - userservice
      - projectservice

networks:
  projectmanager-network: