version: '3'
services:

  projectmanagermysqldb:
    image: mysql:8
    networks:
      - projectmanager-network
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
      - MYSQL_DATABASE=pmsdb 

  discoveryservice:
    image: pmdiscoveryservice
    ports:
      - "8081:8081"
    networks:
      - projectmanager-network
  
  user-service:
    image: projectmanageruser
    networks:
      - projectmanager-network
    environment:
      - spring.profiles.active=dockerDb
    depends_on:
      - projectmanagermysqldb
      - discoveryservice
      
  project-service:
    image: projectmanagerproject
    networks:
      - projectmanager-network
    environment:
      - spring.profiles.active=dockerDb
    depends_on:
      - projectmanagermysqldb
      - discoveryservice
      
  zuuiapigateway:
    image: pmzuuiapigateway
    ports:
      - "8095:8095"
    environment:
      - server.port=8095
    networks:
      - projectmanager-network
    depends_on:
      - discoveryservice
      -  user-service
      -  project-service
       
  projectmanagerui:
    image: projectmanagerui
    ports:
      - "4200:4200"
    networks:
      - projectmanager-network
    depends_on:
      -  user-service
      -  project-service


networks:
  projectmanager-network: